// Package bootstrap implements the bootstrapping logic: generation of a .go file to
// launch the actual generator and launching the generator itself.
//
// The package may be preferred to a command-line utility if generating the serializers
// from golang code is required.
package bootstrap

import (
	"fmt"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const pkgEasyJSON = "github.com/mailru/easyjson"
const genPackage = "github.com/mailru/easyjson/gen"
const pkgWriter = "github.com/mailru/easyjson/jwriter"
const pkgLexer = "github.com/mailru/easyjson/jlexer"

type FileInfo struct {
	Types   []string
	OutName string
}

type Generator struct {
	PkgPath, PkgName string

	FileInfoList []FileInfo

	NoStdMarshalers       bool
	SnakeCase             bool
	LowerCamelCase        bool
	OmitEmpty             bool
	DisallowUnknownFields bool

	BuildTags string

	StubsOnly  bool
	LeaveTemps bool
	NoFormat   bool
}

// writeStub outputs an initial stub for marshalers/unmarshalers so that the package
// using marshalers/unmarshales compiles correctly for boostrapping code.
func (g *Generator) writeStub(types []string, outName string) error {
	f, err := os.Create(outName)
	if err != nil {
		return err
	}
	defer f.Close()

	if g.BuildTags != "" {
		fmt.Fprintln(f, "// +build ", g.BuildTags)
		fmt.Fprintln(f)
	}
	fmt.Fprintln(f, "// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package")
	fmt.Fprintln(f, "// compilable during generation.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "package ", g.PkgName)

	if len(types) > 0 {
		fmt.Fprintln(f)
		fmt.Fprintln(f, "import (")
		fmt.Fprintln(f, `  "`+pkgWriter+`"`)
		fmt.Fprintln(f, `  "`+pkgLexer+`"`)
		fmt.Fprintln(f, ")")
	}

	sort.Strings(types)
	for _, t := range types {
		fmt.Fprintln(f)
		if !g.NoStdMarshalers {
			fmt.Fprintln(f, "func (", t, ") MarshalJSON() ([]byte, error) { return nil, nil }")
			fmt.Fprintln(f, "func (*", t, ") UnmarshalJSON([]byte) error { return nil }")
		}

		fmt.Fprintln(f, "func (", t, ") MarshalEasyJSON(w *jwriter.Writer) {}")
		fmt.Fprintln(f, "func (*", t, ") UnmarshalEasyJSON(l *jlexer.Lexer) {}")
		fmt.Fprintln(f)
		fmt.Fprintln(f, "type EasyJSON_exporter_"+t+" *"+t)
	}
	return nil
}

func (g *Generator) buildHeader() string {
	imports := map[string]string{
		pkgWriter:       "jwriter",
		pkgLexer:        "jlexer",
		pkgEasyJSON:     "easyjson",
		"encoding/json": "json",
		"fmt":           "fmt",
		"time":          "time",
	}

	var sb = &strings.Builder{}
	if g.BuildTags != "" {
		fmt.Fprintln(sb, "// +build ", g.BuildTags)
		fmt.Fprintln(sb)
	}
	fmt.Fprintln(sb, "// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.")
	fmt.Fprintln(sb)
	fmt.Fprintln(sb, "package ", g.PkgName)
	fmt.Fprintln(sb)

	byAlias := map[string]string{}
	var aliases []string
	for path, alias := range imports {
		aliases = append(aliases, alias)
		byAlias[alias] = path
	}

	sort.Strings(aliases)
	fmt.Fprintln(sb, "import (")
	for _, alias := range aliases {
		fmt.Fprintf(sb, "  %s %q\n", alias, byAlias[alias])
	}

	fmt.Fprintln(sb, ")")
	fmt.Fprintln(sb, "")
	fmt.Fprintln(sb, "// suppress unused package warning")
	fmt.Fprintln(sb, "var (")
	fmt.Fprintln(sb, "   _ *json.RawMessage")
	fmt.Fprintln(sb, "   _ *jlexer.Lexer")
	fmt.Fprintln(sb, "   _ *jwriter.Writer")
	fmt.Fprintln(sb, "   _ easyjson.Marshaler")
	fmt.Fprintln(sb, "   _ fmt.Stringer")
	fmt.Fprintln(sb, "   _ time.Time")
	fmt.Fprintln(sb, ")")

	fmt.Fprintln(sb)
	return sb.String()
}

// writeMain creates a .go file that launches the generator if 'go run'.
func (g *Generator) writeMain() (path string, err error) {
	first := g.FileInfoList[0]
	f, err := ioutil.TempFile(filepath.Dir(first.OutName), "easyjson-bootstrap-")
	if err != nil {
		return "", err
	}

	fmt.Fprintln(f, "// +build ignore")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch")
	fmt.Fprintln(f, "// the actual generator.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "package main")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "import (")
	fmt.Fprintln(f, `  "fmt"`)
	fmt.Fprintln(f, `  "os"`)
	fmt.Fprintln(f)
	fmt.Fprintf(f, "  %q\n", genPackage)
	for _, fi := range g.FileInfoList {
		if len(fi.Types) > 0 {
			fmt.Fprintln(f)
			fmt.Fprintf(f, "  pkg %q\n", g.PkgPath)
			break
		}
	}
	fmt.Fprintln(f, ")")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "func main() {")
	for i := 0; i < len(g.FileInfoList); i++ {
		fmt.Fprintf(f, "  if err := genCode%d(); err != nil {\n", i)
		fmt.Fprintln(f, "    fmt.Fprintln(os.Stderr, err)")
		fmt.Fprintln(f, "    os.Exit(1)")
		fmt.Fprintln(f, "  }")
	}
	fmt.Fprintln(f, "}")

	header := g.buildHeader()
	for i, fi := range g.FileInfoList {
		fmt.Fprintln(f)
		fmt.Fprintf(f, "func genCode%d() error {\n", i)
		fmt.Fprintf(f, "  g := gen.NewGenerator(%q)\n", filepath.Base(fi.OutName))
		fmt.Fprintf(f, "  g.SetPkg(%q, %q)\n", g.PkgName, g.PkgPath)
		if g.BuildTags != "" {
			fmt.Fprintf(f, "  g.SetBuildTags(%q)\n", g.BuildTags)
		}
		if g.SnakeCase {
			fmt.Fprintln(f, "  g.UseSnakeCase()")
		}
		if g.LowerCamelCase {
			fmt.Fprintln(f, "  g.UseLowerCamelCase()")
		}
		if g.OmitEmpty {
			fmt.Fprintln(f, "  g.OmitEmpty()")
		}
		if g.NoStdMarshalers {
			fmt.Fprintln(f, "  g.NoStdMarshalers()")
		}
		if g.DisallowUnknownFields {
			fmt.Fprintln(f, "  g.DisallowUnknownFields()")
		}

		sort.Strings(fi.Types)
		for _, v := range fi.Types {
			fmt.Fprintln(f, "  g.Add(pkg.EasyJSON_exporter_"+v+"(nil))")
		}

		fmt.Fprintf(f, "  f, err := os.Create(%q + \".tmp\")\n", fi.OutName)
		fmt.Fprintln(f, "  if err != nil {")
		fmt.Fprintln(f, "    return err")
		fmt.Fprintln(f, "  }")
		fmt.Fprintln(f)
		if !g.LeaveTemps {
			fmt.Fprintln(f, "  defer os.Remove(f.Name()) // will not remove after rename")
			fmt.Fprintln(f)
		}

		fmt.Fprint(f, `  fmt.Fprintf(f, "%s", `)
		fmt.Fprintf(f, "`%s`", header)
		fmt.Fprintln(f, ")")
		fmt.Fprintln(f, "  if err := g.Run(f); err != nil {")
		fmt.Fprintln(f, "    fmt.Fprintln(os.Stderr, err)")
		fmt.Fprintln(f, "    os.Exit(1)")
		fmt.Fprintln(f, "  }")

		fmt.Fprintf(f, "  if err := os.Rename(f.Name(), %q); err != nil {\n", fi.OutName)
		fmt.Fprintln(f, "    return err")
		fmt.Fprintln(f, "  }")
		fmt.Fprintln(f)
		fmt.Fprintln(f, "  return nil")
		fmt.Fprintln(f, "}")
	}

	src := f.Name()
	if err := f.Close(); err != nil {
		return src, err
	}

	dest := src + ".go"
	return dest, os.Rename(src, dest)
}

func (g *Generator) Run() error {
	for _, fi := range g.FileInfoList {
		if err := g.writeStub(fi.Types, fi.OutName); err != nil {
			return err
		}
	}
	if g.StubsOnly {
		return nil
	}

	path, err := g.writeMain()
	if err != nil {
		return err
	}
	if !g.LeaveTemps {
		defer os.Remove(path)
	}

	cmd := exec.Command("go", "run", "-tags", g.BuildTags, filepath.Base(path))
	cmd.Stderr = os.Stderr
	cmd.Dir = filepath.Dir(path)
	if err = cmd.Run(); err != nil {
		return err
	}

	if !g.NoFormat {
		var files []string
		for _, fi := range g.FileInfoList {
			files = append(files, fi.OutName)
		}
		cmd = exec.Command("gofmt", append([]string{"-w"}, files...)...)
		cmd.Stderr = os.Stderr
		cmd.Stdout = os.Stdout

		if err = cmd.Run(); err != nil {
			return err
		}
	}

	return nil
}
